package com.cos.entity;
// Generated 2018-3-18 15:29:44 by Hibernate Tools 3.2.2.GA

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "cos")
public class AdminEntity implements java.io.Serializable {

	private int id;
	private String name;
	private String departments;
	private BigInteger telephone;
	private String organization;

	public AdminEntity() {
	}

	public AdminEntity(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public AdminEntity(int id, String name, String departments, BigInteger telephone, String organization) {
		this.id = id;
		this.name = name;
		this.departments = departments;
		this.telephone = telephone;
		this.organization = organization;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "departments", length = 20)
	public String getDepartments() {
		return this.departments;
	}

	public void setDepartments(String departments) {
		this.departments = departments;
	}

	@Column(name = "telephone")
	public BigInteger getTelephone() {
		return this.telephone;
	}

	public void setTelephone(BigInteger telephone) {
		this.telephone = telephone;
	}

	@Column(name = "organization", length = 20)
	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

}
