package com.cos.entity;
// Generated 2018-3-18 15:29:44 by Hibernate Tools 3.2.2.GA

import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "cos")
@DynamicInsert(true)
@DynamicUpdate(true)
public class StudentEntity implements java.io.Serializable {

	private int id;
	private String name;
	private Integer sex;
	private String area;
	private String departments;
	private String major;
	private BigInteger telephone;
	private String organization;
	private String hobby;
	private String evaluation;
	private Date deliveryTime;
	private Integer isPass;
	private Integer isDelivery;

	public StudentEntity() {
	}

	public StudentEntity(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public StudentEntity(int id, String name, Integer sex, String area, String departments, String major, BigInteger telephone,
			String organization, String hobby, String evaluation, Date deliveryTime, Integer isPass,
			Integer isDelivery) {
		this.id = id;
		this.name = name;
		this.sex = sex;
		this.area = area;
		this.departments = departments;
		this.major = major;
		this.telephone = telephone;
		this.organization = organization;
		this.hobby = hobby;
		this.evaluation = evaluation;
		this.deliveryTime = deliveryTime;
		this.isPass = isPass;
		this.isDelivery = isDelivery;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Column(name = "area", length = 20)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "departments", length = 20)
	public String getDepartments() {
		return this.departments;
	}

	public void setDepartments(String departments) {
		this.departments = departments;
	}

	@Column(name = "major", length = 20)
	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	@Column(name = "telephone")
	public BigInteger getTelephone() {
		return this.telephone;
	}

	public void setTelephone(BigInteger telephone) {
		this.telephone = telephone;
	}

	@Column(name = "organization", length = 20)
	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	@Column(name = "hobby")
	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	@Column(name = "evaluation")
	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deliveryTime", length = 19)
	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	@Column(name = "isPass")
	public Integer getIsPass() {
		return this.isPass;
	}

	public void setIsPass(Integer isPass) {
		this.isPass = isPass;
	}

	@Column(name = "isDelivery")
	public Integer getIsDelivery() {
		return this.isDelivery;
	}

	public void setIsDelivery(Integer isDelivery) {
		this.isDelivery = isDelivery;
	}

}
