package com.cos.entity;
// Generated 2018-3-18 14:55:08 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Useraccess generated by hbm2java
 */
@Entity
@Table(name = "useraccess", catalog = "cos")
public class UserAccessEntity implements java.io.Serializable {

	private int userId;
	private String userName;
	private String passWord;
	private int permission;

	public UserAccessEntity() {
	}

	public UserAccessEntity(int userId, String userName, String passWord, int permission) {
		this.userId = userId;
		this.userName = userName;
		this.passWord = passWord;
		this.permission = permission;
	}

	@Id

	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "userName", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "passWord", nullable = false, length = 20)
	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	@Column(name = "permission", nullable = false)
	public int getPermission() {
		return this.permission;
	}

	public void setPermission(int permission) {
		this.permission = permission;
	}

}
